flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- snaplet-sqlite-simple-1.0.0.2
- snap-1.0.0.1
- heist-1.0.1.0
- map-syntax-0.2.0.2
resolver: lts-8.17
nix:
  enable: false
  packages: [ gd libpng zlib fontconfig freetype libjpeg expat ]
